var sentiment = require('sentiment');
var sqlite3 = require('sqlite3').verbose(); 
var express = require('express');
var billboardapi = express();
var db = new sqlite3.Database('./billboard.db') 

billboardapi.get('/', function(req, res) {
      res.send('Hello World')
})

billboardapi.get('/billboard', function(req, res) {
      db.all('SELECT rowid, rank, song, artist, year, lyrics, source, sentiment  FROM billboard', 
      function(err, rows) {
            if(err) {
                  console.log(err)
            } else {
                 res.json(rows)
                 
            }
      })
})

// create server

var http = require('http');
var server = billboardapi.listen(8080, ()=>{console.log("Server listening on port 8080")})

process.on('SIGINT', () => { //closes db when node receives SIGINT signal. SIGINT is generated by ctrl-c on all platforms
      console.log('closing server on 8080')
      db.close();
      server.close();
  });

// export server for testing
module.exports = server;